# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - "*"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: $[ variables['Build.BuildNumber'] ]
  buildTag: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
  suffix: $(Date:yyyyMMdd)

jobs:
- job: "Windows_Build"
  pool:
    vmImage: 'windows-2022'
  condition: |
      not(
        or (
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          eq(variables['buildTag'], True)
          )
        )
  steps:
  - template: azure/build.yml

- job: "Windows_deploy"
  pool:
    vmImage: "windows-2022"
  condition: |
      and (
        succeeded(),
        or (
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          eq(variables['buildTag'], True)
        )
      )
  steps:
      - template: azure/build.yml
      - template: azure/deploy.yml